dependencies:
  # - <organization/repository name>@<version>

  # https://github.com/smartcontractkit/chainlink-brownie-contracts
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

# Load the environment variable file as this holds the PRIVATE_KEY
dotenv: .env

networks:
  default: development      #When you don't specify a network, brownie defaults to this.
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True #Flag for whether the contract is published and verified
  mainnet-fork-dev:   #The price feed address is from Chainlink Ethereum data feeds
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
